workflows:
  name: hello_orka
  steps:
    - id: intro
      provider: echo
      input:
        user_input: "Orka is a YAML-first orchestrator for AI workflows."

    - id: shout
      provider: uppercase
      input:
        user_input: ${intro.output}

    - id: finale
      provider: reverse
      input:
        user_input: "💡 ${shout.output}"
